<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/dist/js/app.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/jquery-pjax/jquery.pjax.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/nprogress/nprogress.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/nestable/jquery.nestable.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/toastr/build/toastr.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/bootstrap3-editable/js/bootstrap-editable.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/sweetalert2/dist/sweetalert2.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/laravel-admin/laravel-admin.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/iCheck/icheck.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/colorpicker/bootstrap-colorpicker.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/input-mask/jquery.inputmask.bundle.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/moment/min/moment-with-locales.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/bootstrap-fileinput/js/fileinput.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/select2/select2.full.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/number-input/bootstrap-number-input.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/iCheck/icheck.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/AdminLTE/plugins/ionslider/ion.rangeSlider.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/bootstrap-switch/dist/js/bootstrap-switch.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/fontawesome-iconpicker/dist/js/fontawesome-iconpicker.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/vendor/laravel-admin/bootstrap-duallistbox/dist/jquery.bootstrap-duallistbox.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/packages/ckeditor/ckeditor.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/packages/ckeditor/adapters/jquery.js')}}" type="text/javascript"></script>