<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
return view('welcome');
}); 
Route::get('index',[
'as'=>'index',
'uses'=>'controllerPage@getIndex'
]);
Route::get('collection_women/{type}',[
'as'=>'collection_women',
'uses'=>'controllerPage@getCollectionWomen'
]);
Route::get('listingMenu',[
'as'=>'listingMenu',
'uses'=>'controllerPage@getListingMenu'
]); 
Route::get('customerInformation',[
'as'=>'getCustomerInformation',
'uses'=>'controllerPage@getCustomerInformation'
]);
Route::get('shippingMethod',[
'as'=>'getShippingMethod',
'uses'=>'controllerPage@getShippingMethod'
]);
Route::get('paymentMethod',[
'as'=>'getPaymentMethod',
'uses'=>'controllerPage@getPaymentMethod'
]);
Route::get('blog',[
'as'=>'getBlog',
'uses'=>'controllerPage@getBlog'
]); 
Route::post('blog',[
'as'=>'postCheckLike',
'uses'=>'controllerPage@postCheckLike'
]);

Route::post('blog',[
'as'=>'postBlog',
'uses'=>'controllerPage@postBlog'
]);
Route::get('contact',[
'as'=>'contact',
'uses'=>'controllerPage@getContact'
]);
Route::post('contact',[
'as'=>'postContact',
'uses'=>'controllerPage@postContact'
]);
Route::get('likeTest01/{id}',[
'as'=>'getLikeTest01',
'uses'=>'controllerPage@getLikeTest01'
]);
Route::post('likeTest02',[
'as'=>'postLikeTest02',
'uses'=>'controllerPage@postLikeTest02'
]);
////
Route::get('payment',[
'as'=>'postPayment',
'uses'=>'controllerPage@postPayment'
]);
///// tesst

// Comment
// 
Auth::routes();
Route::get('commnetTest/{id}',[
'as'=>'getcomment',
'uses'=>'controllerPage@getComment'
]);
Route::post('commnetTest/{id}',[
'as'=>'postcomment',
'uses'=>'controllerPage@postComment'
]);
// end comment
Route::get('register',[
'as'=>'signin',
'uses'=>'controllerPage@getSignin'
]);
Route::post('register',[
'as'=>'signin',
'uses'=>'controllerPage@postSignin'
]);
Route::get('loginPage',[
'as'=>'loginPage',
'uses'=>'controllerPage@getLoginPage'
]);
Route::post('loginPage',[
'as'=>'loginPage',
'uses'=>'controllerPage@postLoginPage'
]);
Route::get('updateAcc',[
'as'=>'getUpdateAcc',
'uses'=>'controllerPage@getUpdateAcc'
]);
Route::post('updateAcc',[
'as'=>'postUpdateAcc',
'uses'=>'controllerPage@postUpdateAcc'
]);
Route::get('dang-xuat',[
'as'=>'logout',
'uses'=>'controllerPage@postLogout'
]);
Route::get('search',[
'as'=>'getSearch',
'uses'=>'controllerPage@getSearch'
]);

/*
Route::get('listing',[
'as'=>'listing',
'uses'=>'controllerPage@getListing'
]);
*/
Route::get('productTitle/{id}',[
'as'=>'productTitle',
'uses'=>'controllerPage@getProductTitle'
]);
Route::get('cart',[
'as'=>'cart',
'uses'=>'controllerPage@getCart'
]);
Route::get('add-to-cart/{id}',[
'as'=>'addCart',
'uses'=>'controllerPage@getAddCart'
]);
Route::post('get-add-to-cart/{id}',[
'as'=>'AddCartTitle',
'uses'=>'controllerPage@getAddCartTitle'
]);
Route::get('del-cart/{id}',[
'as'=>'deleteCart',
'uses'=>'controllerPage@getDeleteCart'
]);
Route::get('update-cart/{id}/{qty}',[
'as'=>'updateCart',
'uses'=>'controllerPage@getUpdateCart'
]);
Route::get('order',[
'as'=>'orders',
'uses'=>'controllerPage@getOrder'
]);
Route::post('order',[
'as'=>'orders',
'uses'=>'controllerPage@postOrder'
]);
//
//
//
//
// Admin
//
//
//
//
Route::get('indexAdmin',[
'middleware'=>'auth',
'as'=>'indexAdmin',
'uses'=>'PageAdminController@getIndexAdmin'
]);


//end dassboad
Route::get('addSmallCategory',[
	'middleware'=>'auth',
'as'=>'getaddSmallCategory',
'uses'=>'ControllerSmallCategories@getaddSmallCategories'
]);
Route::post('addSmallCategory',[
	'middleware'=>'auth',
'as'=>'postaddSmallCategory',
'uses'=>'ControllerSmallCategories@postAddSmallCategories'
]);
// start small categories
// 
// 
// 
Route::get('smallCategory',[
	'middleware'=>'auth',
'as'=>'smallCategory',
'uses'=>'ControllerSmallCategories@getSmallCategories'
]);
Route::get('addSmallCategory',[
	'middleware'=>'auth',
'as'=>'getaddSmallCategory',
'uses'=>'ControllerSmallCategories@getaddSmallCategories'
]);
Route::post('addSmallCategory',[
	'middleware'=>'auth',
'as'=>'postaddSmallCategory',
'uses'=>'ControllerSmallCategories@postAddSmallCategories'
]);
Route::get('editSmallCategory/{id}',[
	'middleware'=>'auth',
'as'=>'geteditSmallCategory2',
'uses'=>'ControllerSmallCategories@getEditSmallCategory'
]);
Route::post('editSmallCategory/{id}',[
	'middleware'=>'auth',
'as'=>'posteditSmallCategory',
'uses'=>'ControllerSmallCategories@postEditSmallCategory'
]);
Route::get('deleteSmallCategory/{id}',[

'as'=>'getdeleteSmallCategory',
'uses'=>'ControllerSmallCategories@getDeleteSmallCategory'
]);
// end small categories
// 
// 
// 
// Categories
Route::get('categories',[
	'middleware'=>'auth',
'as'=>'categories',
'uses'=>'ControllerCategories@getCategories'
]);
Route::get('addCategories',[
	'middleware'=>'auth',
'as'=>'getaddCategories',
'uses'=>'ControllerCategories@getAddCategories'
]);
Route::post('addCategories',[
'as'=>'postaddCategories',
'uses'=>'ControllerCategories@postAddCategories'
]);
Route::get('editCategory/{id}',[
	'middleware'=>'auth',
'as'=>'geteditCategory',
'uses'=>'ControllerCategories@getEditCategory'
]);
Route::post('editCategory/{id}',[
'as'=>'posteditCategory',
'uses'=>'ControllerCategories@postEditCategory'
]);
Route::get('deleteCategory/{id}',[
'as'=>'getdeleteCategory',
'uses'=>'ControllerCategories@getDeleteCategory'
]);
// end categories
// 
// start image
Route::get('imageProduct',[
	'middleware'=>'auth',
'as'=>'imageProduct',
'uses'=>'ControllerImage@getImageProduct'
]);
Route::get('addImageProduct',[
	'middleware'=>'auth',
'as'=>'getAddImageProduct',
'uses'=>'ControllerImage@getAddImageProduct'
]);
Route::post('addImageProduct',[
'as'=>'postAddImageProduct',
'uses'=>'ControllerImage@postAddImageProduct'
]);
Route::get('editImage/{id}',[
	'middleware'=>'auth',
'as'=>'getEditImageProduct',
'uses'=>'ControllerImage@getEditImageProduct'
]);
Route::post('editImage/{id}',[
'as'=>'postEditImageProduct',
'uses'=>'ControllerImage@postEditImageProduct'
]);
Route::get('deleteImage/{id}',[
'as'=>'getDeleteImageProduct',
'uses'=>'ControllerImage@getDeleteImageProduct'
]);
// end image
// orrder
Route::get('manaOrder',[
	'middleware'=>'auth',
'as'=>'getManagementOrder',
'uses'=>'controllerOrder@getManagementOrder'
]);
Route::get('editManagementOrder2/{id}',[
	'middleware'=>'auth',
'as'=>'getEditManagementOrder2',
'uses'=>'controllerOrder@getEditManagementOrder2'
]);
Route::get('orderStatus',[
	'middleware'=>'auth',
'as'=>'getOrderStatus',
'uses'=>'controllerOrder@getOrderStatus'
]);
Route::post('checkOrder',[
'as'=>'postCheckOrder',
'uses'=>'controllerOrder@postCheckOrder'
]);
Route::get('manaComment',[
	'middleware'=>'auth',
'as'=>'getManaComment',
'uses'=>'ControllerRequest@getManaComment'
]);
Route::get('deleteComment/{id}',[
'as'=>'getDeleteComment',
'uses'=>'ControllerRequest@getDeleteComment'
]);
//end order
//
//
//start account
//
Route::get('loginAdmin',[
'as'=>'login',
'uses'=>'controllerAccount@getLoginAdmin'
]);
Route::post('loginAdmin',[
'as'=>'login',
'uses'=>'controllerAccount@postLoginAdmin'
]);
Route::get('logout',[
'as'=>'logoutAdmin',
'uses'=>'controllerAccount@postLogoutAdmin'
]);

// start customers
Route::get('customer',[
	'middleware'=>'auth',
'as'=>'getCustomer',
'uses'=>'controllerAccount@getCustomer'
]);
Route::get('addCustomer',[
	'middleware'=>'auth',
'as'=>'getAddCustomer',
'uses'=>'controllerAccount@getAddCustomer'
]);
Route::post('addCustomer',[
'as'=>'postAddCustomer',
'uses'=>'controllerAccount@postAddCustomer'
]);
Route::get('editCustomer/{id}',[
	'middleware'=>'auth',
'as'=>'geteditCustomer',
'uses'=>'controllerAccount@geteditCustomer'
]);
Route::post('editCustomer/{id}',[
'as'=>'posteditCustomer',
'uses'=>'controllerAccount@posteditCustomer'
]);
Route::get('deleteCustomer/{id}',[
'as'=>'getdeleteCustomer',
'uses'=>'controllerAccount@getdeleteCustomer'
]);
//
//
//start employess
Route::get('employess',[
	'middleware'=>'auth',
'as'=>'getemployess',
'uses'=>'controllerAccount@getEmployess'
]);
Route::get('addemployess',[
	'middleware'=>'auth',
'as'=>'getAddEmployess',
'uses'=>'controllerAccount@getAddEmployess'
]);
Route::post('addemployess',[
'as'=>'postAddEmployess',
'uses'=>'controllerAccount@postAddEmployess'
]);
Route::get('editemployess/{id}',[
	'middleware'=>'auth',
'as'=>'geteditEmployess',
'uses'=>'controllerAccount@getEditEmployess'
]);
Route::post('editemployess/{id}',[
'as'=>'posteditEmployess',
'uses'=>'controllerAccount@postEditEmployess'
]);
Route::get('deleteemployess/{id}',[
'as'=>'getdeleteEmployess',
'uses'=>'controllerAccount@getDeleteEmployess'
]);
//end account
//
// start contact
Route::get('contactAdmin',[
	'middleware'=>'auth',
'as'=>'getContact',
'uses'=>'controllerContact@getContact'
]);
Route::get('deleteContact/{id}',[
'as'=>'getDeleteContact',
'uses'=>'controllerContact@getDeleteContact'
]);
// end contact
// start product
Route::get('products',[
	'middleware'=>'auth',
'as'=>'products',
'uses'=>'ControllerProduct@getproduct'
]);
Route::get('addProduct',[
	'middleware'=>'auth',
'as'=>'getAddProduct', 
'uses'=>'ControllerProduct@getAddProduct'
]);
Route::post('addProduct',[
'as'=>'postAddProduct',
'uses'=>'ControllerProduct@postAddProduct'
]);
Route::get('addProduct2',[
	'middleware'=>'auth',
'as'=>'getAddProduct2', 
'uses'=>'ControllerProduct@getAddProduct2'
]);
Route::post('addProduct2',[
'as'=>'postAddProduct2',
'uses'=>'ControllerProduct@postAddProduct2'
]);
Route::get('editProducts/{id}',[
	'middleware'=>'auth',
'as'=>'getEditProduct',
'uses'=>'ControllerProduct@getEditProduct'
]);
Route::post('editProducts/{id}',[
'as'=>'postEditProduct',
'uses'=>'ControllerProduct@postEditProduct'
]);
Route::get('deleteProducts/{id}',[
'as'=>'getDeleteProducts',
'uses'=>'ControllerProduct@getDeleteProducts'
]);
/// end product
/// 
/// 
/// start request
/// 
Route::get('request',[
	'middleware'=>'auth',
'as'=>'request',
'uses'=>'ControllerRequest@getRequest'
]);
Route::get('addRequest',[
	'middleware'=>'auth',
'as'=>'getAddRequest',
'uses'=>'ControllerRequest@getAddRequest'
]);
Route::post('addProduct',[
'as'=>'postAddRequest',
'uses'=>'ControllerRequest@postAddRequest'
]);
Route::get('editRequest/{id}',[
	'middleware'=>'auth',
'as'=>'getEditRequest',
'uses'=>'ControllerRequest@getEditRequest'
]);
Route::post('editRequest/{id}',[
'as'=>'postEditRequest',
'uses'=>'ControllerRequest@postEditRequest'
]);
Route::get('deleteRequest/{id}',[
'as'=>'getDeleteRequest',
'uses'=>'ControllerRequest@getDeleteRequest'
]);
// end request 
Route::get('demo',[
'as'=>'demo',
'uses'=>'ControllerCategories@getdemo'
]);
// end Admin
// new Admin 
// 
// 
// 
Route::get('dashboard',[
'as'=>'dashboard',
'uses'=>'PageAdminController@getDashboard'
]);
Route::get('banner',[
'as'=>'banner',
'uses'=>'PageAdminController@getBanner'
]);
Route::get('language',[
'as'=>'language',
'uses'=>'PageAdminController@getLanguager'
]);
Route::get('shop_brand',[
'as'=>'shop_brand',
'uses'=>'PageAdminController@getShop_brand'
]);
Route::get('shop_category',[
'as'=>'shop_category',
'uses'=>'PageAdminController@getShop_category'
]);
Route::get('shop_customer',[
'as'=>'shop_customer',
'uses'=>'PageAdminController@getShop_customery'
]);
Route::get('shop_order',[
'as'=>'shop_order',
'uses'=>'PageAdminController@getShop_order'
]);
Route::get('shop_product',[
'as'=>'shop_product',
'uses'=>'PageAdminController@getShop_productr'
]);
Route::get('shop_shipping',[
'as'=>'shop_shipping',
'uses'=>'PageAdminController@getShop_shipping'
]);
Route::get('shop_shipping_status',[
'as'=>'shop_shipping_status',
'uses'=>'PageAdminController@getShop_shipping_status'
]);
Route::get('shop_special_price',[
'as'=>'shop_special_price',
'uses'=>'PageAdminController@getShop_special_price'
]);

Route::get('setting', function () {
return view('viewAdmin.setting');
});
Route::get('setting',[
'as'=>'setting',
'uses'=>'PageAdminController@getSetting'
]);
// end newAdmin
